<style>
	ul {
		list-style-type: none;
		padding: 0;
		margin: 0;
		overflow: hidden;
		background-color: #4C3F91;"
	}
	li {
		float: left;
	}
	li a {
		display: block;
		color: white;
		text-align: center;
		padding: 10px 10px;
		text-decoration: none;
	}
	li a:hover {
		background-color: #9145B6;
	}

	table, th, td {
		border: 1px solid black;
		border-collapse: collapse;
	}
	th {
		background-color: #76BA99;
	}
	tr:nth-child(even) {
		background-color: #FFDCAE;
	}

	input[type=submit] {
		background-color: #76BA99;
		border: solid 2px #76BA99;
		color: black;
		padding: 10px 10px;
		text-decoration: none;
		margin: 4px 2px;
		cursor: pointer;
		border-radius: 20px;
		font-weight: bold;
	}
	input[type=submit]:hover {
		background-color: #FFDCAE;
	}

	.selection {
		background-color: #76BA99;
		border: solid 2px #76BA99;
		color: black;
		padding: 10px 10px;
		text-decoration: none;
		margin: 4px 2px;
		cursor: pointer;
		border-radius: 20px;
		font-weight: bold;
	}
	.selection:hover {
		background-color: #FFDCAE;
		border: solid 2px #76BA99;
	}
</style>

<nav>
	<ul>
		<li><a href="../task9.php">&laquo Back to Task 9</a></li>
	</ul>
</nav>